// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWerhZTFUCETX4HPmLgwM1FIDpirYaZG8',
    appId: '1:381666447421:web:9d6b090583d11299ea1a54',
    messagingSenderId: '381666447421',
    projectId: 'who-s-sus',
    authDomain: 'who-s-sus.firebaseapp.com',
    databaseURL: 'https://who-s-sus-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'who-s-sus.firebasestorage.app',
    measurementId: 'G-6PK3TS8QCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr9jAJHWmtRhgWkQvkeRLGx2XM-Ey9ipE',
    appId: '1:381666447421:android:8e48e8d2396d778cea1a54',
    messagingSenderId: '381666447421',
    projectId: 'who-s-sus',
    databaseURL: 'https://who-s-sus-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'who-s-sus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0s_Wt3OumTrYoc_rmmd7WhKM6gby0iPw',
    appId: '1:381666447421:ios:86557cdb41041826ea1a54',
    messagingSenderId: '381666447421',
    projectId: 'who-s-sus',
    databaseURL: 'https://who-s-sus-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'who-s-sus.firebasestorage.app',
    iosBundleId: 'com.example.wordimposter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0s_Wt3OumTrYoc_rmmd7WhKM6gby0iPw',
    appId: '1:381666447421:ios:86557cdb41041826ea1a54',
    messagingSenderId: '381666447421',
    projectId: 'who-s-sus',
    databaseURL: 'https://who-s-sus-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'who-s-sus.firebasestorage.app',
    iosBundleId: 'com.example.wordimposter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWerhZTFUCETX4HPmLgwM1FIDpirYaZG8',
    appId: '1:381666447421:web:00e40bc8ee096968ea1a54',
    messagingSenderId: '381666447421',
    projectId: 'who-s-sus',
    authDomain: 'who-s-sus.firebaseapp.com',
    databaseURL: 'https://who-s-sus-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'who-s-sus.firebasestorage.app',
    measurementId: 'G-P6VH8FG3RT',
  );
}
